[tool.poetry]
authors = ["Your Name <you@example.com>"]
description = ""
name = "djongo-tracks"
version = "0.1.0"

[tool.poetry.dependencies]
Django = "^3.1.7"
djongo = {git = "git@github.com:nesdis/djongo.git"}
graphene-django = "^2.15.0"
python = "^3.8"

[tool.poetry.dev-dependencies]
black = {version = "^20.8b1", allow-prereleases = true}

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
